/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.modules.opentimestamps;

import org.sleuthkit.autopsy.ingest.IngestModuleGlobalSettingsPanel;
/**
 *
 * @author Developer
 */
public class OpentimestampsGlobalSettingsPanel extends IngestModuleGlobalSettingsPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer OpentimestampsGlobalSettingsPanel
     */
    public OpentimestampsGlobalSettingsPanel() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    @Override
    public void saveSettings() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
