/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.modules.opentimestamps;

import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettings;
import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettingsPanel;

/**
 *
 * @author Developer
 */
public class OpentimestampsJobSettingsPanel extends IngestModuleIngestJobSettingsPanel implements java.beans.Customizer {
    
    private Object bean;
    private OpentimestampsSettings settings;
    
//    private VirusTotalOnlineCheckSettings settings;
//
//    VirusTotalOnlineCheckJobSettingsPanel(VirusTotalOnlineCheckSettings settings) {
//        initComponents();
//        this.settings = settings;
//        this.apiKeyTextField.setText(settings.getApiKey());
//    }
    /**
     * Creates new customizer OpentimestampsJobSettingsPanel
     */
    public OpentimestampsJobSettingsPanel(OpentimestampsSettings settings) {
        initComponents();
        this.settings = settings;
        this.calendarTextArea.setText(settings.getCalendarString());
        this.btcConfTextArea.setText(settings.getBtcConfPath());
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btcConfTextArea = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        calendarTextArea = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Custom calendar server URLs");

        jLabel2.setText("bitcoin.conf location");

        btcConfTextArea.setToolTipText("Leave empty for default");
        btcConfTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcConfTextAreaActionPerformed(evt);
            }
        });
        btcConfTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btcConfTextAreaKeyTyped(evt);
            }
        });

        calendarTextArea.setColumns(20);
        calendarTextArea.setRows(5);
        calendarTextArea.setToolTipText(" Comma seperate values. Leave empty for defaults");
        calendarTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calendarTextAreaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(calendarTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(btcConfTextArea))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btcConfTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btcConfTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcConfTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcConfTextAreaActionPerformed

    private void calendarTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarTextAreaKeyTyped
        settings.setCalendarString(calendarTextArea.getText());
    }//GEN-LAST:event_calendarTextAreaKeyTyped

    private void btcConfTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btcConfTextAreaKeyTyped
        settings.setBtcConfPath(btcConfTextArea.getText());
    }//GEN-LAST:event_btcConfTextAreaKeyTyped
    
    @Override
    public IngestModuleIngestJobSettings getSettings() {
        return settings;
        //return settings;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btcConfTextArea;
    private javax.swing.JTextArea calendarTextArea;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
