/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.modules.opentimestamps;

import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettings;
import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettingsPanel;

/**
 *
 * @author Developer
 */
public class OpentimestampsJobSettingsPanel extends IngestModuleIngestJobSettingsPanel implements java.beans.Customizer {
    
    private Object bean;
    
//    private VirusTotalOnlineCheckSettings settings;
//
//    VirusTotalOnlineCheckJobSettingsPanel(VirusTotalOnlineCheckSettings settings) {
//        initComponents();
//        this.settings = settings;
//        this.apiKeyTextField.setText(settings.getApiKey());
//    }
    /**
     * Creates new customizer OpentimestampsJobSettingsPanel
     */
    public OpentimestampsJobSettingsPanel() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    @Override
    public IngestModuleIngestJobSettings getSettings() {
        return null;
        //return settings;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
